spring.application.name=chat-sphere

server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/chatsphere}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:Dileep@123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:ThisIsASecretKeyForChatSphereJwtAuthenticationChangeLater123456}
jwt.expiration=86400000